### PR TITLE
PHP 7 Support

### PR DESCRIPTION
**Pull request by fntlnz**

### CODE REVIEW

**Comment by leodido** [comment]
:+1:

**Comment by mentalstring** [comment]
Not sure if this feedback is still useful for someone. I've managed to compile this with PHP 7.3 on a recent system with some tweaks:

* cld2 had to be compiled with `CFLAGS="-Wno-narrowing"`
* it complained about libtool version mismatch, but this seems to fix it:
```
phpize
aclocal
libtoolize --force
autoreconf
```

However, one of the tests doesn't pass:
```
PASS CLD2Detector Tests [tests/cld2_detector.phpt] 
PASS CLD2Encoding Tests [tests/cld2_encoding.phpt] 
FAIL CLD2Language Tests [tests/cld2_language.phpt] 
```

```
$ php tests/cld2_language.phpt 
--TEST--
CLD2Language Tests
--DESCRIPTION--
Tests CLD2Language static methods and properties
--SKIPIF--
--FILE--
int(7)
string(7) "ITALIAN"
string(7) "ENGLISH"
string(3) "pam"
Segmentation fault
```


The extension is still usable nonetheless, although I'm getting ocasional odd results, like reported in https://github.com/fntlnz/cld2-php-ext/issues/2.

It would be nice if all the info reported by cld2 (list of all languages, chunks, etc) was accessible but I haven't found a way.

Regardless, thank you @fntlnz for your work on this.

**Comment by fntlnz** [comment]
Hey @mentalstring !
Do you think you would be able to send a PR to the readme with these details ? I think it would be a cool thing to do a refresh to this repo if people still use this code. I personally have a couple of projects still in production with this too

**Comment by mentalstring** [comment]
I've submitted a couple of things that made it build on my systems.

I have made some tests with the particular commit [you mentioned](https://github.com/fntlnz/cld2-php-ext/issues/2#issuecomment-201980782), but it only got one of the reports examples to work — the other one returns unknown language instead of French.

Would be really cool to get this working as it's the only effort I'm aware of to bring CLD2 into PHP. Unfortunately I'm unable to help with the extension itself, but can help with testing as I have a large set of sample texts to run it against.

**Pull request closed without merging**
